sudo: false
language: java
jdk:
- oraclejdk8

before_install:
- sudo apt-get -qq update
- sudo apt-get install -y libxml2-utils
script: mvn clean install
after_success:
- bash <(curl -s https://codecov.io/bash)  
- bash .travis/environment.sh

deploy:
  provider: releases
  api_key:
    secure: ZblXEdzMZqzABW1D9HAPVae9QWSc8mZjpBoeXDJyjdokfzvujCzowb+5uLCzcDGzRr0MY9h+M0EwGua5IAzGmMO1MgMitX+8Mg7NB3M+zVBrLo7euU99qyNJr8ApIHuttqGNg2cEwp6RS6g2OKYjS0BJwCHDIk27mgR2DW6MOlPuTx+vSM8deebCcjV19Kxl/0AXslyOUFll9cghEdErMSehYReeh5U6fSUMBXYhdz8/8Kj/HVgm/sgOA97GsYg1E0HHiKRECibLo/Oes/lDZuytYRsLAXpfYGDLiPFCLOEjPDXsX7fFkbOvMbm8i5fCYedUjJ7zuYvhwit8ADt852R/vYc6YWzP+0e6jq7jTkefHt+JcWHVyJMvQE+o5q8WnetAHCL1GDGZ0c4qcGBVhrvR25PylDfJHdxCjFOBVKnPrU/HTELPnDMF1mqlO+n4LYDkSwuc13NR27RPSSSwPiADJbr1pVe+4m2fAHYmPinXCyDopnIEgjFaChZOGa2ZoRhfaZ4evsN2QIJH41q+EXb7CYedNO41zKo/8/+xoQmDsCi4pJi6xsxYaHDz507MyXXJxeutYyP1P05P+DnObB/L1jALKus9iRbNLVyDo7Bl77318HOCjAbxDTDWmLbx/xbEU+CHVLCmKMkBviEx3hlH41c15ioTVcrtG0zUGvk=
  file: target/release/RandomTPs.jar
  skip_cleanup: true  
  on:
    tags: true
  
notifications:
  email: false

env:    
  global:
  - ENCRYPTION_LABEL: 5795a2fbb362
  - COMMIT_AUTHOR_EMAIL: juli_sesena@hotmail.com
  - secure: Uo1fazawW5T9ltHFZGS/PI9e/tIrJmQvM6RuFcDY2J6O+ephLC8zR9qbtOkmXtTHdBxurGMCRmHcJzpY1uHEmm+uUVbki8k+0y5tgc2DjbfPYrVcwnXzj3yN2bPqretn3AHtMr1bs8KxPFDPXBQfZbFakvh3AbVx+dAD04OluExsG3YBY3KYGYkM1NlvrRc6U2gP/ZrcRKktPvFmrp4umzCkp9yDBrlHedNCSFigyAb/XE9PlMaGcZDTJdaske56+ExHW2xTW9KvjhVAH7IQKN7cakya8XbwHezziD/9yiXHKanE+4cjHf9XRiUMEEkoYd3e68E1zjy0qut7FZirod/6COhrKaR0mlyXsaiSrXMIUpmTnPEXnR3sHJ7FzLVXM4yADGfpng+cCexqpitch/DhQYWALg6V078VMg4gDRG/gxX1ERtzU1+Qjd2Vs1a6q0FtV+51Jyb+5IqBVou0qRGincOu7LnlTvj7idLrJXmn+8NXAk2wgUdmjXsWCdqgij7N8MRrEZLvH+eNEOtH64NVLYIi6qfc7orn+Rby/DckhDnrbs7nCm9R77r/bJLpIrIhdq+FuDCekbqQcIvuawYWO9H13JlnI+AW4S9dloCPnrMXCAYddoB0XlxY5FnJ9juQstESWl9GxmGnN1MjFIVFk/Sv2V7qXbl2OMVhRQg=
  - secure: edlVMXlTAgJMuRmQ1iPUxD0gIarguSE+5O+05d+CrBtAZyrTZT96EtfC0vatZTH4fd5LOeZ0hHbxlR3tz9hjNjkhfvN8NXxhHaJtdeJpeNiOQR36Qv5IE99/2F1aUxrWtmcvmMnhrhN9RI5g9tAqIlN+KPxH6EuF5YLJ4ZucmHiUMOv9BXfr216ob+0bALZmfR/vtvwgrVQISSEhfGlrAZQVuHI9f3z//sNV2GFGT8jGFyxlEg2B5ZXba/mAYaihcvQsnBD1S6PAf4RvXz0EkoUcELDhfNO9CYIHqcaVOeY/Yqeh3M2X9h48XnD32oX0Nn4LTw9LyeS9IvDDRTVqLRbfz9HrZESAzX/eohCeYiBt48xf67XqB6WxGoJedCrcrlnjzYxvgvXP4++Y/qbsYWQ25KerCKyvwCYuPWN2dgzKWHjEVmhP8k+MLkT/VSKhccVBZxSjd9Uo6uwJOY3+JqLvMQATM8Py2H/g1zfPQkBBR/62f2m3F4mpNdFsLPUr3sopTPb0MpqBJACYxdp9Oo3dpFl40EoPaMPpBn7ovlB/9FuFmNnI8am1ts9UlSa7yDDkTnHoAWFOW9J8KdG8x/SxT+td6cz3L2JuWG5u7SY9/s7Bgj8uMQLCRbp2J+7oaeTFZi6JPWj29ETEa662iqRkZussSiyTuMfmd0oYQ1E=