sudo: false
language: java
jdk:
  - openjdk7

script: mvn clean install
after_success:
  - bash <(curl -s https://codecov.io/bash)  
  - bash .utility/environment.sh

deploy:
  provider: releases
  api_key:
    secure: fPrvaH921p1efOjvqDwI6O3Sw905ymuQTs3In2hG87SqPSRg8eZzlx2BmVoV/RG9lR7hi4lWDVg93/oCTVwS2h1pr8CgE8UHRg6257I4+5SKZ7WIluK7s1Jo2bHSV9E3qnjBr8wcypMqfUzO2RsbqWnPk2NzczI7Lj5/fHbo42h4s53gOgxEsD5KL8Xrt//52mud1Upl9Q/5sxYiwsXAc7aOAyTSVI5Sj6kwWqnHHwwQLL2qs5TFv/vORCtT++k4oyg4IxaaGc2mkXuis9zq8JV2Eglwn6nA3RUdskvCym6s6sbMtyr0K8HAX5WCj32GJx9Ubh7jkSTjKEVauFXPIG3S6H61RPOKumzFrbXZcyRbIqxvRxplGrXUiDzYSdfzH587HhHLUvsmDu+xI+/xT2/9Y/WvPBUxG6pG4QvzCEtCGV6lBmy24nDfBIiPlgs834EocjOKVlJto8mSY3m58sLMItBx8lsWe81jRGtYJDN96BM8bds4SvN/mTs1Jwr9+WLhMtDw5xIekAJp7DXpSG9D3fmal/ddG/1TJkOEv6ugfqCE7+UwvqQfeDuu4PIOhW2sVYOujxAJDQbCCLZ8+B4gVfSPX+ndy40v/h+/5jc0dhdcve3P/tFOCC8iDdx8eUA1tPM9Q5cZkVTtIT/HH9nVE9zWGuGR1zpMffg3RX8=
  file: target/release/RandomTPs.jar
  on:
    tags: true
  
notifications:
  email: false

env:    
  global:
  - secure: "h2OVfEH11QIKoF3aMgA6M7/c1mK1etGi1rmYQmUceiyxPE7+4MqISpt9ruGd7l4bOaxipjW6mGZdpTQYx5RmzLQHH4Ven+FOQndi5n34DT89XyjDP7mBoTsQ4GrlKy5CM5qXprvz7EQ749CgZ7rdRAW3TGWUQG05qqDnuNDs4m3uxf+2l+jcmrpVx5T9LOT+HnHc1FeX7m0F70QN7c6tDyn9KR9JLsW5yscsQ8Gr7gi28T6HIvF+fP01xAop0Fxd+R7LiEOhhnBsV2keLjc3K20KJvWe6xl8tSMUvsB7vycnAFbfGbtOX3OsZqWErpnkP/+hulQ6jXSiW9+56LaElhaia/M/Rrie1Cjvg0t57ShFQBrAAgMt/TNBAUqlsNbjbgDuHP91JkUDkWxgJPc2AWZpUA1Z9QnoqvTrnVM9YDnFbz8EadZE+wp1x8cceYj+qh//uZ6xkf8buMX2SmGFAahfgYf5rUQDz1X62xnhmvwEj92zt4CsZiWzC/yeeVTKGWT7tevg6rBccIpKsGf0RdaE+V4BhOtDDoa/UObmyhGwtEQRRURYReoyGSYVX91A0BpZzci7bdkUPKCQz2u344xIrhduNqDOOBvKS2/PpfNBrIeoojHVxjMf8OJZmdcVfY3QIoB0yhs+gyvkMxEKPEszwJk+1nCyzWPRH9zC1l0="
  - secure: "Uo1fazawW5T9ltHFZGS/PI9e/tIrJmQvM6RuFcDY2J6O+ephLC8zR9qbtOkmXtTHdBxurGMCRmHcJzpY1uHEmm+uUVbki8k+0y5tgc2DjbfPYrVcwnXzj3yN2bPqretn3AHtMr1bs8KxPFDPXBQfZbFakvh3AbVx+dAD04OluExsG3YBY3KYGYkM1NlvrRc6U2gP/ZrcRKktPvFmrp4umzCkp9yDBrlHedNCSFigyAb/XE9PlMaGcZDTJdaske56+ExHW2xTW9KvjhVAH7IQKN7cakya8XbwHezziD/9yiXHKanE+4cjHf9XRiUMEEkoYd3e68E1zjy0qut7FZirod/6COhrKaR0mlyXsaiSrXMIUpmTnPEXnR3sHJ7FzLVXM4yADGfpng+cCexqpitch/DhQYWALg6V078VMg4gDRG/gxX1ERtzU1+Qjd2Vs1a6q0FtV+51Jyb+5IqBVou0qRGincOu7LnlTvj7idLrJXmn+8NXAk2wgUdmjXsWCdqgij7N8MRrEZLvH+eNEOtH64NVLYIi6qfc7orn+Rby/DckhDnrbs7nCm9R77r/bJLpIrIhdq+FuDCekbqQcIvuawYWO9H13JlnI+AW4S9dloCPnrMXCAYddoB0XlxY5FnJ9juQstESWl9GxmGnN1MjFIVFk/Sv2V7qXbl2OMVhRQg="
  - secure: "edlVMXlTAgJMuRmQ1iPUxD0gIarguSE+5O+05d+CrBtAZyrTZT96EtfC0vatZTH4fd5LOeZ0hHbxlR3tz9hjNjkhfvN8NXxhHaJtdeJpeNiOQR36Qv5IE99/2F1aUxrWtmcvmMnhrhN9RI5g9tAqIlN+KPxH6EuF5YLJ4ZucmHiUMOv9BXfr216ob+0bALZmfR/vtvwgrVQISSEhfGlrAZQVuHI9f3z//sNV2GFGT8jGFyxlEg2B5ZXba/mAYaihcvQsnBD1S6PAf4RvXz0EkoUcELDhfNO9CYIHqcaVOeY/Yqeh3M2X9h48XnD32oX0Nn4LTw9LyeS9IvDDRTVqLRbfz9HrZESAzX/eohCeYiBt48xf67XqB6WxGoJedCrcrlnjzYxvgvXP4++Y/qbsYWQ25KerCKyvwCYuPWN2dgzKWHjEVmhP8k+MLkT/VSKhccVBZxSjd9Uo6uwJOY3+JqLvMQATM8Py2H/g1zfPQkBBR/62f2m3F4mpNdFsLPUr3sopTPb0MpqBJACYxdp9Oo3dpFl40EoPaMPpBn7ovlB/9FuFmNnI8am1ts9UlSa7yDDkTnHoAWFOW9J8KdG8x/SxT+td6cz3L2JuWG5u7SY9/s7Bgj8uMQLCRbp2J+7oaeTFZi6JPWj29ETEa662iqRkZussSiyTuMfmd0oYQ1E="