## Plugin YAML file
name: RandomTPs
version: 1.0.0
description: Random teleport plugin
database: false
website: alternacraft.github.io/RandomTPs/

author: AlternaCraft

main: com.alternacraft.randomtps.Main.RandomTPs

commands:
    randomtps:
        description: Main command of the plugin
        usage: /<command>
        aliases: rt

permissions:
    rt.*:
      description: Get access to all commands
      children:
        rt.info: true
        rt.zone: true
        rt.purge: true  
        rt.reload: true            
    rt.info:
        description: Show plugin commands
        default: true
    rt.zone:
        description: Manage a region
        default: false
    rt.purge:
        description: Clean configuration
        default: false
    rt.reload:
        description: Reload the plugin
        default: false