## Plugin YAML file
name: RandomTPs
version: 1.1.0
description: Random teleport plugin
database: false
website: alternacraft.github.io/RandomTPs/

author: AlternaCraft

main: com.alternacraft.randomtps.Main.RandomTPs

commands:
    randomtps:
        description: Main command of the plugin
        usage: /<command>
        aliases: rtp
        permission: rtp.help

permissions:
    rtp.*:
      description: Get access to all commands
      children:
        rtp.help: true
        rtp.info: true
        rtp.zone: true
        rtp.purge: true  
        rtp.reload: true            
    rtp.help:
        description: Commands list
        default: true
    rtp.info:
        description: Plugin information
        default: true
    rtp.zone:
        description: Manage a region
        default: op     
    rtp.purge:
        description: Remove inactive zones
        default: op
    rtp.reload:
        description: Reload the plugin configuration
        default: op