## Plugin YAML file
name: RandomTPs
version: 1.0.1
description: Random teleport plugin
database: false
website: alternacraft.github.io/RandomTPs/

author: AlternaCraft

main: com.alternacraft.randomtps.Main.RandomTPs

commands:
    randomtps:
        description: Main command of the plugin
        usage: /<command>
        aliases: rtp

permissions:
    rtp.*:
      description: Get access to all commands
      children:
        rt.info: true
        rt.zone: true
        rt.purge: true  
        rt.reload: true            
    rtp.info:
        description: Show plugin commands
        default: true
    rtp.zone:
        description: Manage a region
        default: false     
    rtp.purge:
        description: Clean configuration
        default: false
    rtp.reload:
        description: Reload the plugin
        default: false